name: BackEnd_SonarQube

on:
  workflow_call:    

jobs:
  BackEnd_Build:
    
    name: Qualite BackEnd
    
    runs-on: ubuntu-latest
        
    steps:

      # - uses: actions/checkout@v6

      - name: Qualite BackEnd
        run: |
          echo "Analyzing BackEnd application with SonarQube"