name: FrontEnd_SonarQube

on:
  workflow_call:    

jobs:
  FrontEnd_SonarQube:
    
    name: Qualite FrontEnd
    
    runs-on: ubuntu-latest
        
    steps:
      
      # - uses: actions/checkout@v6

      - name: Qualite FrontEnd
        run: |
          echo "Analyzing FrontEnd application with SonarQube"