name: Snyk_Scan

on:
  workflow_call:    

jobs:
  
  Snyk_BackEnd:
    name: SAST BackEnd
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6
          
      - name: SAST BackEnd
        run: |
          echo "Scanning BackEnd dependencies"

  Snyk_FrontEnd:
    name: SAST FrontEnd
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6
          
      - name: SAST FrontEnd
        run: |
          echo "Scanning FrontEnd dependencies"