name: Continuous Integration

on:
  workflow_call:
    # Manage secrets for the called workflow
    # Example :
    # secrets:
    #     SONAR_TOKEN_BACKEND:
    #       required: false
        
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: read
  
jobs:
  Check-variables:
    
    runs-on: ubuntu-latest
    
    steps:      
      
      - name: Show caller & called workflow branch
        run: |
          echo "Triggered by : ${{ github.event_name }}"
          echo "Action       : ${{ github.event.action }}"

          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
         
          echo "Caller branch: ${{ github.ref_name }}"
          echo "Called pipeline branch: main"

  BackEnd_Build:    
    needs:
      - Check-variables
    uses: ./.github/workflows/01_1_BackEnd_Build.yml
    secrets: inherit
    
  BackEnd_Test:    
    needs:
      - BackEnd_Build
    uses: ./.github/workflows/01_2_BackEnd_Test.yml
    secrets: inherit

  BackEnd_SonarQube:    
    needs:
      - BackEnd_Test
    uses: ./.github/workflows/01_3_BackEnd_SonarQube.yml
    secrets: inherit
    
  FrontEnd_Build:    
    needs:
      - Check-variables
    uses: ./.github/workflows/01_4_FrontEnd_Build.yml
    secrets: inherit

  FrontEnd_Test:    
    needs:
      - FrontEnd_Build
    uses: ./.github/workflows/01_5_FrontEnd_Test.yml
    secrets: inherit

  FrontEnd_SonarQube:    
    needs:
      - FrontEnd_Test
    uses: ./.github/workflows/01_6_FrontEnd_SonarQube.yml
    secrets: inherit

  Snyk_Scan:    
    needs:
      - BackEnd_Build
      - FrontEnd_Build
    uses: ./.github/workflows/01_7_Snyk.yml
    secrets: inherit

  CI_Status:
    
    name: CI Status
    
    runs-on: ubuntu-latest

    needs:
      - BackEnd_Build
      - BackEnd_Test
      - FrontEnd_Build
      - FrontEnd_Test
      - BackEnd_SonarQube
      - FrontEnd_SonarQube
      - Snyk_Scan

    if: always()

    steps:
      - run: echo "All checks passed"