name: Deployment application

on:
  workflow_call:
    
    # secrets:
        # AWS credentials are required to deploy the infrastructure
        # AWS_ACCESS_KEY_ID:
        #   required: true
        # AWS_SECRET_ACCESS_KEY:
        #   required: true
      
    inputs:
      environment:
        required: true
        type: string      

permissions:
  contents: read  

jobs:
  
  deploy-monitoring:

    runs-on: ubuntu-latest
    
    name: Deploy Monitoring Stack

    environment: ${{ inputs.environment }}
    

    steps:      

      - name: Create monitoring namespace
        run: |
          echo "Deploying monitoring stack in ${{ inputs.environment }} environment"
      